import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
  container: { backgroundColor: '#f3f4f6', flex: 1},
  header: {
    backgroundColor: '#2563eb', color: '#fff', padding: 16, paddingTop: 32, flexDirection: 'row',
    justifyContent: 'space-between', alignItems: 'center', borderBottomLeftRadius: 16, borderBottomRightRadius: 16,
  }, 
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  logoCircle: { width: 36, height: 36, backgroundColor: '#fff', borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: '600' },
  headerSubtitle: { color: '#fff', fontSize: 12, opacity: 0.9, maxWidth: 160, lineHeight: 14 },
  headerRight: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  iconBtn: { marginRight: 8, position: 'relative' },
  dot: { position: 'absolute', top: 2, right: 2, width: 8, height: 8, backgroundColor: '#ef4444', borderRadius: 4, borderWidth: 1, borderColor: '#2563eb' },
  langBtn: { backgroundColor: 'rgba(255,255,255,0.2)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  alertBox: { backgroundColor: '#fff7ed', borderColor: '#fdba74', borderWidth: 1, padding: 12, borderRadius: 12, flexDirection: 'row', gap: 12, alignItems: 'flex-start', marginTop: 16 },
  alertIcon: { backgroundColor: '#f97316', width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' },
  alertText: { color: '#9a3412', fontSize: 14, flex: 1 },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  statCard: { flex: 1, paddingVertical: 16, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  statNumber: { color: '#fff', fontSize: 22, fontWeight: 'bold', marginBottom: 4 },
  statLabel: { color: '#fff', fontSize: 12, opacity: 0.9 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#1f2937', marginTop: 24, marginBottom: 10 },
  servicesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'space-between' },
  serviceCard: { backgroundColor: '#fff', padding: 16, borderRadius: 12, alignItems: 'center', flexBasis: '48%', marginBottom: 12, borderWidth: 1, borderColor: 'transparent' },
  activeBorder: { borderColor: '#3b82f6', borderWidth: 2 },
  iconSq: { width: 40, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  serviceTitle: { fontSize: 15, color: '#1f2937', marginBottom: 4, fontWeight: '600' },
  serviceDesc: { fontSize: 13, color: '#6b7280' },
  updatesCard: { backgroundColor: '#fff', padding: 16, borderRadius: 12, marginTop: 24 },
  updateItem: { flexDirection: 'row', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  updateDot: { width: 8, height: 8, borderRadius: 4, marginTop: 6 },
  updateContent: { flex: 1 },
  updateHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  updateText: { fontSize: 14, color: '#1f2937', flex: 1 },
  badge: { backgroundColor: '#e5e7eb', fontSize: 12, paddingHorizontal: 6, borderRadius: 4, color: '#374151', fontWeight: '500' },
  updateTime: { fontSize: 12, color: '#9ca3af' },
  resourcesSection: { backgroundColor: '#eff6ff', padding: 16, borderRadius: 12, marginTop: 24 },
  resourceButtons: { flexDirection: 'row', gap: 12 },
  resBtn: { flex: 1, backgroundColor: '#fff', padding: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginHorizontal: 2, fontWeight: '500' },
  aiBanner: { backgroundColor: '#2563eb', borderRadius: 16, padding: 20, flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 24 },
  aiIconCircle: { width: 50, height: 50, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 25, alignItems: 'center', justifyContent: 'center' },
  aiText: { flex: 1 },
  aiTitle: { fontSize: 16, color: '#fff', fontWeight: '600', marginBottom: 4 },
  aiDesc: { fontSize: 13, color: '#fff', opacity: 0.9, marginBottom: 8 },
  statusBadge: { backgroundColor: '#4ade80', color: '#064e3b', fontSize: 12, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, fontWeight: '600', alignSelf: 'flex-start' },
  shadowCard: {
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
});

export default globalStyles;
